### ISSUE TITLE
error while performing /setup

### ISSUE THREAD

**Issue by sidboy55555** [e-enes/discord-invite-tracker#10]
Hi,

I have just installed and connected the bot to discord and the database successful. but while performing the /setup command, the bot logs the following:

```
/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1268
    return errors.length === 0 ? Result.ok(finalObject) : Result.err(new CombinedPropertyError(errors));
                                                                     ^

CombinedPropertyError: Received one or more errors
    at ObjectValidator.handleIgnoreStrategy (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1268:70)
    at ObjectValidator.handleStrategy (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1121:47)
    at ObjectValidator.handle (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1221:17)
    at ObjectValidator.parse (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:212:88)
    at EmbedBuilder.setFooter (/srv/bots/invite/node_modules/@discordjs/builders/dist/index.js:333:26)
    at Object.run (/srv/bots/invite/dist/src/commands/setup.js:68:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    [
      'text',
      CombinedError: Received one or more errors
          at UnionValidator.handle (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1104:23)
          at UnionValidator.run (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:198:23)
          at runPredicate (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1231:32)
          at ObjectValidator.handleIgnoreStrategy (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1241:9)
          at ObjectValidator.handleStrategy (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1121:47)
          at ObjectValidator.handle (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1221:17)
          at ObjectValidator.parse (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:212:88)
          at EmbedBuilder.setFooter (/srv/bots/invite/node_modules/@discordjs/builders/dist/index.js:333:26)
          at Object.run (/srv/bots/invite/dist/src/commands/setup.js:68:18)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
        errors: [
          ExpectedValidationError: Expected values to be equals
              at LiteralValidator.handle (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:745:76)
              at LiteralValidator.run (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:198:23)
              at UnionValidator.handle (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1099:32)
              at UnionValidator.run (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:198:23)
              at runPredicate (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1231:32)
              at ObjectValidator.handleIgnoreStrategy (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1241:9)
              at ObjectValidator.handleStrategy (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1121:47)
              at ObjectValidator.handle (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1221:17)
              at ObjectValidator.parse (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:212:88)
              at EmbedBuilder.setFooter (/srv/bots/invite/node_modules/@discordjs/builders/dist/index.js:333:26) {
            validator: 's.literal(V)',
            given: '',
            expected: null
          },
          ExpectedConstraintError: Invalid string length
              at Object.run (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1546:79)
              at StringValidator.run (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:202:27)
              at UnionValidator.handle (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1099:32)
              at UnionValidator.run (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:198:23)
              at runPredicate (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1231:32)
              at ObjectValidator.handleIgnoreStrategy (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1241:9)
              at ObjectValidator.handleStrategy (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1121:47)
              at ObjectValidator.handle (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:1221:17)
              at ObjectValidator.parse (/srv/bots/invite/node_modules/@sapphire/shapeshift/dist/index.js:212:88)
              at EmbedBuilder.setFooter (/srv/bots/invite/node_modules/@discordjs/builders/dist/index.js:333:26) {
            constraint: 's.string.lengthGreaterThanOrEqual',
            given: '',
            expected: 'expected.length >= 1'
          }
        ]
      }
    ]
  ]
}

```

**Comment by e-enes** [comment]
Hello,

You haven't properly filled out the `config.ts` file; the "footer" field must have a value.

For any configuration-related issues, you can DM me on Discord at `e.enes`. Some features are currently not supported by the bot. If you have any suggestions, please consider starting a discussion instead of creating an issue.

Best regards,
Enes Tahiri
