### ISSUE TITLE
TokenInvalid error

### ISSUE THREAD

**Issue by sidboy55555** [e-enes/discord-invite-tracker#9]
Hi again,

While starting the bot it gives a TokenInvalid error, While I entered the right token inside .env, which is inside dist.
```
/srv/bots/invite# npm start

> discord-invite-tracker@1.2.5 start
> node dist/src/index.js

/srv/bots/invite/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136
    const invalidToken = new DiscordjsError(ErrorCodes.TokenInvalid);
                         ^

Error [TokenInvalid]: An invalid token was provided.
    at WebSocketManager.connect (/srv/bots/invite/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136:26)
    at Client.login (/srv/bots/invite/node_modules/discord.js/src/client/Client.js:226:21)
    at Object.<anonymous> (/srv/bots/invite/dist/src/index.js:59:8)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'TokenInvalid'
}

Node.js v20.5.1
```

Generated a fresh pair two times, without any luck.

**Comment by e-enes** [comment]
Hello,

Could you try launching the bot with the `.env` file placed outside of the `dist/` folder? In this project, the path to the `.env` file isn't explicitly configured, which means that the dotenv library may default to looking for it at the root of the project, especially if it's not in a production environment (where it would be `dist/` only). The behavior of dotenv can vary based on its configuration and the environment in which it's running.

If this adjustment doesn't solve the problem, may I please see the structure of your dist folder? This will help me understand if there are any other configuration issues or path discrepancies affecting the bot's operation.

_And yes, I know, I really need to change this method of starting the bot.  Sorry for the inconvenience. 🙄_

Kind regards,
Enes Tahiri

**Comment by sidboy55555** [comment]
Hi,

I don't mind for the inconvenience, atleast this helps the project! :D
So far I saw this is the only decent selfhosted discord invite tracker bot out there so happy to help.

These are my ls outputs:

```
/srv/bots/invite# ls
LICENSE  README.md  config.ts  dist  node_modules  package-lock.json  package.json  src  tsconfig.json
```

```
/srv/bots/invite/dist# ls
config.js  src
```

```
/srv/bots/invite/dist/src# ls
buttons  client.js  commands  events  index.js  types.js  utils
```

After `npm install` I used `npm run build` and after just pasted de .env in every folder you see. and I tried to start the bot from all three folders with `npm start` and also with `node path/index.js`. all six tries without luck.

**Comment by e-enes** [comment]
Hello, 

I don't see any `.env` file in `srv/bot/invite/`. Can you create it and complete the information in the format of the `.env.example`?

```
# Discord Bot Info
TOKEN=

# MySQL Server Info
HOST=
PORT= # default 3306
USERNAME=
PASSWORD=
DATABASE=
```

Let me know if this solved the problem. 

Kind regards,
Enes Tahiri

**Comment by sidboy55555** [comment]
Oops well yes ls doesn't show files which start with a dot. but the file is in there, in all three folders.

**Comment by e-enes** [comment]
Can you do an `ls -a`? 

And can you also check that your `.env` looks like this

![Image 13-01-24 à 13 12](https://github.com/e-enes/discord-invite-tracker/assets/125091714/c3dd2a64-ce22-411f-bab9-059215b2e6a7)

**Comment by sidboy55555** [comment]
I've found the issue. Apparently, I was using an older generated token. Some .env files had a different token, so I replaced them all with a new one. Now, it gets past the token check.

However, the MySQL database connection doesn't seem to be working. Connecting to the database from the command line with the same user and password works. Also, other bots are able to connect using this user (though they use a different database).

error:
```
/srv/bots/invite# npm start

> discord-invite-tracker@1.2.5 start
> node dist/src/index.js

/srv/bots/invite/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'bot'@'localhost' (using password: YES)
    at Sequence._packetToError (/srv/bots/invite/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/srv/bots/invite/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/srv/bots/invite/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/srv/bots/invite/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/srv/bots/invite/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/srv/bots/invite/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/srv/bots/invite/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/srv/bots/invite/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    --------------------
    at Protocol._enqueue (/srv/bots/invite/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/srv/bots/invite/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/srv/bots/invite/node_modules/mysql/lib/Connection.js:116:18)
    at Connection._implyConnect (/srv/bots/invite/node_modules/mysql/lib/Connection.js:454:10)
    at Connection.query (/srv/bots/invite/node_modules/mysql/lib/Connection.js:196:8)
    at initDatabase (/srv/bots/invite/dist/src/utils/mysql.js:58:19)
    at Object.execute (/srv/bots/invite/dist/src/events/ready.js:22:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/srv/bots/invite/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:514:28)
    at Protocol._delegateError (/srv/bots/invite/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Handshake.<anonymous> (/srv/bots/invite/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Handshake.emit (node:events:514:28)
    at Sequence.end (/srv/bots/invite/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Handshake.ErrorPacket (/srv/bots/invite/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/srv/bots/invite/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/srv/bots/invite/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/srv/bots/invite/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'bot'@'localhost' (using password: YES)",
  sqlState: '28000',
  fatal: true
}

Node.js v20.5.1
```

and ofcourse mariadb gives the following error: `[Warning] Access denied for user 'bot'@'localhost' (using password: YES)`

**Comment by e-enes** [comment]
The MySQL error 1045 is primarily related to authentication issues. It typically indicates a problem with the setup or configuration of your MySQL database, specifically concerning the credentials – the username and password used for accessing the database. 

This error is not about the bot itself but points to an issue in your database configuration. The most common cause for this error is incorrect login details. To resolve it, you should verify and ensure that the username and password you are using are correct and match the credentials set for the database user in the MySQL server configuration.

cf. https://kinsta.com/knowledgebase/mysql-error-1045/

**Comment by sidboy55555** [comment]
I already know what the issue is, but can't seem to fix it. 

The issue is that I configured `require-secure-transport = on` in mysql. which states that a ssl connection in mandatory.
another selfhosted bot works perfectly fine with this setup, I have changed some of the code of this bot so it should connect with ssl:

.env
```
# MySQL Server Info
HOST=localhost
PORT=3306
USERNAME=bot
PASSWORD=password
DATABASE=invitetracker
VARIABLES=sslidentity=/etc/ssl/bots/ticketsystem.p12&sslpassword=password&sslcert=/etc/ssl/bots/ca.pem
```

mysql.js
```
const options = {
    host: process.env.HOST,
    port: process.env.PORT ? Number(process.env.PORT) : 3306,
    username: process.env.USERNAME,
    password: process.env.PASSWORD,
    database: process.env.DATABASE,
    variables: process.env.VARIABLES,
};
const uri = `mysql://${options.username}:${options.password}@${options.host}:${options.port}/${options.database}?${options.variables}`;
```
